#!/bin/bash
export PATH="/home/jackson/.cargo/bin:$PATH"

# Directory where to store temporary data
TMP_DIR="/home/jackson/.config/rmpc/tmp"

# Ensure the directory is created
mkdir -p "$TMP_DIR"

# Where to temporarily store the album art received from rmpc
ALBUM_ART_PATH="$TMP_DIR/notification_cover"
SONG=$(rmpc song)

ARTIST=$(jq -r '.metadata.artist' <<< "$SONG")
TITLE=$(jq -r '.metadata.title' <<< "$SONG")

# Path to fallback album art if no album art is found by rmpc/mpd
# Change this to your needs
DEFAULT_ALBUM_ART_PATH="$TMP_DIR/default_album_art.jpg"

# Save album art of the currently playing song to a file
if ! rmpc albumart --output "$ALBUM_ART_PATH"; then
    # Use default album art if rmpc returns non-zero exit code
    ALBUM_ART_PATH="${DEFAULT_ALBUM_ART_PATH}"
fi

if [ -n "$TITLE" ]; then # Only if TITLE is not empty
    title_length=${#TITLE} # Get the length of the title
    # Generate a string of hyphens of the same length as the title
    # Using printf for this is efficient:
    title_underline=$(printf '%.0s-' $(seq 1 $title_length))
else
    title_underline="" # No underline if there's no title
fi

NOTIFICATION_BODY="$ARTIST\n$title_underline\n$TITLE"
# Send the notification
notify-send -i "${ALBUM_ART_PATH}" "Now Playing" "$NOTIFICATION_BODY"
